name: waterme
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/happy.jpg
    - assets/weak.jpg
    - assets/dead.jpg
    - assets/shappy.jpg
    - assets/sweak.jpg
    - assets/ssdead.jpg
    - assets/happy.OPUS
    - assets/weak.OPUS
    - assets/dead.OPUS

